apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-lvkc
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/abhindas-tenant/my-app/devfile-sample-lvkc@sha256:82bcf444d9c954ca2af1138b2e22026189f9ab848a681b248359016f2d37cee3
        name: my-nodejs
        resources: {}
status: {}
